### ISSUE TITLE
Wrong localization of the days of the week (Russian language, Ukraine)

### ISSUE THREAD

**Issue by gmikhail** [elementary/wingpanel-indicator-datetime#112]
Instead of a two-letter day of the week, three-letter is used. This is wrong.

![2019-01-03 172554](https://user-images.githubusercontent.com/4838367/50696705-d9d7d080-1048-11e9-85be-7684c49284c6.png)

Important note: localization error only in the Ukrainian locale of the Russian language. In the Russian locale (country Russia), the localization is correct. Thus, you can simply copy the correct days of the week from Russian to Ukrainian locale.

PS: I have long noticed that this bug is present in all popular Linux distributions. If this is possible - inform the problem main localization project. I don’t know where to report, but the problem seems to be affecting many Linux distributions because they use the same translation packages.

**Comment by danrabbit** [comment]
It seems like as far as this can be in this code base, this should be resolved. See #74 and #75 

If this is still incorrect for you, localization fixes need to be submitted to GLib here: https://gitlab.gnome.org/GNOME/glib/tree/master/po

Closing as "Out of Scope" since there's nothing that can be done in this codebase to improve this issue and action must be taken elsewhere instead
