### ISSUE TITLE
Time Format is Wrong on AM/PM Mode

### ISSUE THREAD

**Issue by aimproxy** [elementary/wingpanel-indicator-datetime#170]
When AM/PM Format is selected on Date & Time Settings the date time indicator still on 24h format.

**Comment by danrabbit** [comment]
Are you using both switchboard date time from master and this indicator from master?

**Comment by aimproxy** [comment]
No I didn't use switchboard from master only the indicator. If is that the problem u probably should include this in the issues!

**Comment by aimproxy** [comment]
I updated now the `switchboard-plug-datetime` and the time format still in 24h after change it in Date & Time Settings

**Comment by danrabbit** [comment]
There's a gsettings/accountservice key migration happening right now. It's not really long-term relevant enough to include in the README, but you'll need the (as of yet) unreleased git master version of switchboard-plug-datetime. There is a note in the gsettings schema that the internal `clock-format` key is deprecated.

If you've also installed Greeter from master, you should have the new accountsservice extension and both components will use that for clock format. Otherwise they should fall back to `/org/gnome/desktop/interface/clock-format`. 

Since this isn't really a bug and works properly if you have the in-development versions of relevant components, I'm going to close this issue as "Invalid".
