### ISSUE TITLE
Bad readability for event names in calendar widget

### ISSUE THREAD

**Issue by neauoire** [elementary/wingpanel-indicator-datetime#213]
![Screenshot from 2020-05-15 06-39-29@2x](https://user-images.githubusercontent.com/1455726/81988731-e88bba00-9676-11ea-914d-a7dacff09877.png)

Currently showing up as dark blue on dark grey.

**Comment by neauoire** [comment]
![Screenshot from 2020-05-15 06-48-48@2x](https://user-images.githubusercontent.com/1455726/81989410-23dab880-9678-11ea-84f3-d899b1c4eeb0.png)

I'm not sure how I made it dark, I have Tweaks set to "Prefer Dark Variant", could that be the cause?

![Screenshot from 2020-05-15 06-48-43@2x](https://user-images.githubusercontent.com/1455726/81989473-3ead2d00-9678-11ea-97cb-fa65a1f04f63.png)

**Comment by neauoire** [comment]
I actually thought that's how things look for everybody.

![Screenshot from 2020-05-15 06-50-24@2x](https://user-images.githubusercontent.com/1455726/81989534-61d7dc80-9678-11ea-90f5-112c386df695.png)

**Comment by danrabbit** [comment]
There's a committed fix to make things at least legible, but it's currently unreleased. We don't support forcing the dark stylesheet like this. There is a supported dark mode being worked on for elementary OS 6.

Gonna close this since it's technically fixed in master, but also technically unsupported.

**Comment by neauoire** [comment]
Gotcha, looking forward to OS6!
