### ISSUE TITLE
Can the elementary clock display seconds?

### ISSUE THREAD

**Issue by hanjoss** [elementary/wingpanel-indicator-datetime#40]
I would like the lock-screen clock and the wingpanel clock to show seconds. Is this possible?

**Comment by danrabbit** [comment]
Gonna punt since this is an enhancement not a release blocker

**Comment by Garbee** [comment]
I'd like to pick this up and work on it to try and get it in for Juno. Or at least fairly close to post-stable if we can't make it in for release. Working with the repo (rolled back two commits since I don't have the newer vala) I have a working code pathway. This is at least the underlying pipe to the dconf setting and getting the seconds to show.

However, I notice that @fabianthoma here has a branch with the changes already done (just in an alternate way.) The big difference of note however is how they pull in the setting. They are removing the `ClockSettings` class and instead using `GLib.Settings` to bind to the value changes directly it seems.

A few questions on all of this:

1) What is the status on @fabianthoma's existing patch?
2) Should I be using `GLib.Settings` as well for any patches I attempt to make?
3) This issue also mentions having the Greeter's time work off the same setting. I don't see where that is currently possible. These clock settings are *per user*, so unless we dynamically change the clock format based on the config of the user selected it isn't feasible. We don't have a Greeter settings area (that I can find) to configure the time format for that alone. Are we OK with punting any Greeter changes in regards to this off to a later point and having an issue opened up in that repo to track and discuss that detail further?

**Comment by tintou** [comment]
I don't really understand, is there any particular purpose the show seconds there? How is that even used for in real life?
No judgment, but I want to understand how is that blocking your life…
I would just prefer this component not being force-refreshed every second as it also has some power-consumption drawbacks…

**Comment by Garbee** [comment]
>  how is that blocking your life…

In my case, it isn't "blocking my life" in the slightest. I simply like to have the seconds displayed. Especially in case I feel something is frozen (which my mouse often does get stuck in wingpanel making it look like things are frozen when they aren't.)

> I would just prefer this component not being force-refreshed every second as it also has some power-consumption drawbacks…

This is why the increased refresh rate is *only* triggered when showing seconds is turned on. Otherwise it continues to update at the normal minute interval as it has for years. No performance drawbacks or power drains unless the user opts into this mode.

**Comment by Garbee** [comment]
Any updates here possibly? It's been two weeks and still not a single piece of data to support the power consumption claim made as to why this shouldn't be included in the OS.

I know it's crazy crunch time right before a big OS upgrade, but I get the feeling the team doesn't care to improve the system unless it's in a way that will get applause. No, simply adding the seconds to the clock won't be a major buzz. For some of though us it brings the system in uniformity with every other OS on the planet.

**Comment by fabianthoma** [comment]
@Garbee adding seconds to the clock is already done for some time now in PR #53 it just needs to get merged. 
On a side note: I really don't like the way you are pushing this here. Implementing code even if it's just a little thing takes up valuable time especially when doing this right before a release. So a little thing might wait a few months until it gets implemented, even after reaching a decision about it or looking at the Bug Report. Then getting it past code review (which takes valuable time again) might also take some time.
So please for the future consider that we have a lot to do and even if it does not always seem like it all issues will be looked at when possible.

**Comment by Garbee** [comment]
To try and clarify a little, I'm not that frustrated at the speed of things getting this in. As I said, I understand it's right before a big release. I'm frustrated that it appears the team doesn't care about things unless they directly see benefit personally. Power consumption was provided as a specific reason why this shouldn't be added. Yet when asked for any data to back that up, for two weeks and counting, not a word.

Power consumption is measurable. Yet it seems no measurements have been done or it's not known how to take them. If reasons are provided for why something shouldn't be done that are measurable, data should be provided either on a test already done or on how interested contributors can take the measurements to prove the impact is within a tolerant level.

It seems to me that Elementary development is leaning too far to the human aspect of the spectrum. There isn't enough of a balance with using data to drive decisions. Something I've learned very much working with the Chromium project, is that there is a fine balance here. I think it's something Elementary needs to work on further.

**Comment by tetebueno** [comment]
Hi, is there a chance this is not working anymore?

Some system info:

```
$ dpkg -l | grep wingpanel-indicator-datetime
ii  wingpanel-indicator-datetime               2.2.5+r648+pkg26~ubuntu5.1.5.1                                                 amd64        WingPanel Date & Time Indicator
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	elementary
Description:	elementary OS 5.1.7 Hera
Release:	5.1.7
Codename:	hera
```

Cheers.

**Comment by tintou** [comment]
This is perfectly working for me `gsettings set io.elementary.desktop.wingpanel.datetime clock-show-seconds true` please open a new issue in the future with a mention of the issue if you wish.
