### ISSUE TITLE
Indicator shows only the time and the date is not shown

### ISSUE THREAD

**Issue by ryonakano** [elementary/wingpanel-indicator-datetime#87]
![screenshot from 2018-08-06 19-04-01](https://user-images.githubusercontent.com/26003928/43710781-8f051cfc-99ab-11e8-84d2-d12a535a1ffd.png)

![screenshot from 2018-08-06 19-07-34](https://user-images.githubusercontent.com/26003928/43710907-054e68c8-99ac-11e8-81f3-402d30544b9d.png)

From a few days ago, the indicator shows only the time and the date is not shown. I'm not sure whether this is intentional or a bug, so I'll close in case of the latter. 

On Juno Beta1 (ja_JP)

**Comment by davidmhewitt** [comment]
This will be because of https://github.com/elementary/wingpanel-indicator-datetime/pull/81

The default settings have also been changed to bring the date back, but I guess a new version of the default settings package has not been built/installed yet: https://github.com/elementary/default-settings/pull/94

So, this should fix itself soon.

**Comment by ryonakano** [comment]
Ah, I see. Thank you for telling me.
